jobs:
  include:
    - language: java
      dist: trusty
      java:
        - 'oraclejdk8'
      stage: Test + Build

      install:
        # Download and install kubectl
        - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
        # Install Kind
        - curl -Lo ./kind "https://kind.sigs.k8s.io/dl/v0.8.1/kind-$(uname)-amd64"
        - chmod +x ./kind
        - sudo mv ./kind /usr/local/bin/

      script:
        # Setup E2E env
        - kind create cluster
        - make install-tekton
        - make coverage

      after_success:
        - bash <(curl -s https://codecov.io/bash)
    


